---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    dockerfile: ./Dockerfile.j2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
