---
- name: Tasks | ufw.yml | install ufw with apt
  ansible.builtin.apt:
    name: 'ufw'
    state: 'present'

- name: Tasks | ufw.yml | enable ufw
  community.general.ufw:
    state: enabled

- name: Tasks | ufw.yml | set logging
  community.general.ufw:
    logging: 'on'

- name: Tasks | ufw.yml | block inbound
  community.general.ufw:
    rule: deny
    log: true
